NETWORK_PASSPHRASE="Public Global Stellar Network ; September 2015"
VERSION="1.0.0"

ACCOUNTS=[
  "GDTMEO5J5HSK35KHD7CJBUB576EFVSFXMXHACV7PORO36Z7AIHHKCJH2",
  "GCC3ASQTLRR5DR3QUYQZAXN7VP5NFF5UIUVR6C3TWDJYSMNDERBCDNJ5"
  ]

[DOCUMENTATION]
ORG_NAME="NeonX"
ORG_DBA="NeonX"
ORG_URL="https://neonx-labs.github.io"
ORG_LOGO="https://neonx-labs.github.io/logo.png"
ORG_DESCRIPTION="NEONX aims to become a foundation for future digital innovation."
ORG_OFFICIAL_EMAIL="support@neonx.com"

# =========================
# ASSETS
# =========================

[[CURRENCIES]]
code="NEX"
issuer="GDTMEO5J5HSK35KHD7CJBUB576EFVSFXMXHACV7PORO36Z7AIHHKCJH2"
status="live"
display_decimals=7
name="NeonX"
desc="Utility token powering the NeonX ecosystem on the Stellar network."
conditions="Used for transactions and platform utilities."
image="https://neonx-labs.github.io/logo.png"
is_unlimited=true
